### ISSUE TITLE
properties placeholder in pom.xml

### ISSUE THREAD

**Issue by ghost** [fuinorg/utils4maven#3]
Thank you so much 
How holder when got something like this in pom.xml

<Propetries>
   <version.comms-io>2.5</ <version.comms-io>>
</Propetires>
<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>${version.comms-io}</version>
		</dependency>

**Comment by michael-schnell** [comment]
Where exactly is the variable? Defined in the same file as property like this?

```xml
<properties>
    <utils4jversion>0.9.2</utils4jversion>
</properties>
<dependencies>
    <dependency>
        <groupId>org.fuin</groupId>
        <artifactId>utils4j</artifactId>
        <version>${utils4jversion}</version>
    </dependency>
</dependencies>
```

**Comment by michael-schnell** [comment]
Closed due to inactivity
